// build.mjs — assemble the browser extension's runtime data from the editable
// dictionary JSONs + languages.json. Produces:
//   user/extension/dictionary.js   (globalThis.CLAUDE_L10N)
//   user/extension/languages.json  (enabled languages for the popup)
// Run this after editing any user/dictionaries/*.json.  node build.mjs
import fs from "node:fs";
import path from "node:path";
import { resolveDirection } from "./direction.mjs";
import { LANGUAGES_JSON, DICTS, EXT } from "./paths.mjs";

const registry = JSON.parse(fs.readFileSync(LANGUAGES_JSON, "utf8"));
const enabled = registry.languages.filter((l) => l.enabled && !l.isBase);

const dicts = {};
const langs = [];
for (const lang of enabled) {
  const dictPath = path.join(DICTS, lang.dictionary || `${lang.code}.json`);
  if (!fs.existsSync(dictPath)) { console.warn(`! skip ${lang.code}: missing ${dictPath}`); continue; }
  const d = JSON.parse(fs.readFileSync(dictPath, "utf8"));

  // ---- guard: a literal string that a pattern/plural already covers would SHADOW it.
  // The engine tries strings first, so one date would render in the literal's style and
  // every other date in the pattern's — silently inconsistent. Fail loudly instead.
  {
    const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const res = [];
    for (const p of d.patterns || []) { try { res.push({ re: new RegExp(p.re), src: `pattern «${p.en}»` }); } catch {} }
    for (const [en, spec] of Object.entries(d.plurals || {}))
      for (const pat of [en, spec.plural])
        if (pat) res.push({ re: new RegExp("^" + esc(pat).replace("%d", "(\\d+)") + "$"), src: `plural «${en}»` });
    const clashes = [];
    for (const k of Object.keys(d.strings || {})) {
      const hit = res.find((r) => r.re.test(k));
      if (hit) clashes.push(`   ${JSON.stringify(k)}  ← shadows ${hit.src}`);
    }
    if (clashes.length) {
      console.error(`\n! ${lang.code}: ${clashes.length} literal string(s) shadow a pattern/plural:`);
      console.error(clashes.slice(0, 20).join("\n"));
      console.error("  Remove them from the dictionary — the pattern is the general, consistent form.\n");
      process.exit(1);
    }
  }

  const dir = resolveDirection(lang.code, lang.direction || d._meta?.direction);
  dicts[lang.code] = {
    dir,
    font: lang.font || "",
    strings: d.strings || {},
    plurals: d.plurals || {},
    patterns: d.patterns || [],
  };
  langs.push({ code: lang.code, endonym: lang.endonym, englishName: lang.englishName, direction: dir });
  console.log(`+ ${lang.code} (${dir}): ${Object.keys(d.strings || {}).length} strings`);
}

const payload = { default: registry.default || langs[0]?.code || "ar", langs, dicts };

fs.mkdirSync(EXT, { recursive: true });
const js =
  "/* AUTO-GENERATED by code/toolchain/build.mjs — do not edit by hand. */\n" +
  "/* مُولّد آليًّا — لا تُعدّله يدويًّا. عدّل user/dictionaries/*.json ثم أعد البناء. */\n" +
  "globalThis.CLAUDE_L10N = " + JSON.stringify(payload) + ";\n";
fs.writeFileSync(path.join(EXT, "dictionary.js"), js, "utf8");
fs.writeFileSync(path.join(EXT, "languages.json"), JSON.stringify({ default: payload.default, languages: langs }, null, 2) + "\n", "utf8");

console.log(`\nBuilt ${langs.length} language(s) -> user/extension/dictionary.js`);

// --- versioning: bump the manifest PATCH whenever the total string count changes ---
const manifestPath = path.join(EXT, "manifest.json");
if (fs.existsSync(manifestPath)) {
  const mf = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const total = Object.values(dicts).reduce((a, d) => a + Object.keys(d.strings || {}).length, 0);
  const prev = parseInt((String(mf.version_name || "").match(/(\d+)\s*عبارة/) || [])[1] || "-1", 10);
  if (prev !== total) {
    const p = String(mf.version || "1.0.0").split(".").map((x) => parseInt(x, 10) || 0);
    while (p.length < 3) p.push(0);
    p[2] += 1;
    mf.version = p.join(".");
    mf.version_name = `${mf.version} — قاموس ${total} عبارة`;
    fs.writeFileSync(manifestPath, JSON.stringify(mf, null, 2) + "\n", "utf8");
    console.log(`↑ version -> ${mf.version} (${total} strings)`);
  } else {
    console.log(`= version unchanged (${total} strings)`);
  }
}
