// build.mjs — assemble the browser extension's runtime data from the editable
// dictionary JSONs + languages.json. Produces:
//   user/extension/dictionary.js   (globalThis.CLAUDE_L10N)
//   user/extension/languages.json  (enabled languages for the popup)
// Run this after editing any user/dictionaries/*.json.  node build.mjs
import fs from "node:fs";
import path from "node:path";
import { resolveDirection } from "./direction.mjs";
import { LANGUAGES_JSON, DICTS, EXT } from "./paths.mjs";

const registry = JSON.parse(fs.readFileSync(LANGUAGES_JSON, "utf8"));
const enabled = registry.languages.filter((l) => l.enabled && !l.isBase);

const dicts = {};
const langs = [];
for (const lang of enabled) {
  const dictPath = path.join(DICTS, lang.dictionary || `${lang.code}.json`);
  if (!fs.existsSync(dictPath)) { console.warn(`! skip ${lang.code}: missing ${dictPath}`); continue; }
  const d = JSON.parse(fs.readFileSync(dictPath, "utf8"));

  // ---- guard: a literal string that a pattern/plural already covers would SHADOW it.
  // The engine tries strings first, so one date would render in the literal's style and
  // every other date in the pattern's — silently inconsistent. Fail loudly instead.
  {
    const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const res = [];
    for (const p of d.patterns || []) { try { res.push({ re: new RegExp(p.re), src: `pattern «${p.en}»` }); } catch {} }
    for (const [en, spec] of Object.entries(d.plurals || {}))
      for (const pat of [en, spec.plural])
        if (pat) res.push({ re: new RegExp("^" + esc(pat).replace("%d", "(\\d+)") + "$"), src: `plural «${en}»` });
    const clashes = [];
    for (const k of Object.keys(d.strings || {})) {
      const hit = res.find((r) => r.re.test(k));
      if (hit) clashes.push(`   ${JSON.stringify(k)}  ← shadows ${hit.src}`);
    }
    if (clashes.length) {
      console.error(`\n! ${lang.code}: ${clashes.length} literal string(s) shadow a pattern/plural:`);
      console.error(clashes.slice(0, 20).join("\n"));
      console.error("  Remove them from the dictionary — the pattern is the general, consistent form.\n");
      process.exit(1);
    }
  }

  const dir = resolveDirection(lang.code, lang.direction || d._meta?.direction);
  dicts[lang.code] = {
    dir,
    font: lang.font || "",
    strings: d.strings || {},
    plurals: d.plurals || {},
    patterns: d.patterns || [],
  };
  langs.push({ code: lang.code, endonym: lang.endonym, englishName: lang.englishName, direction: dir });
  console.log(`+ ${lang.code} (${dir}): ${Object.keys(d.strings || {}).length} strings`);
}

const payload = { default: registry.default || langs[0]?.code || "ar", langs, dicts };

fs.mkdirSync(EXT, { recursive: true });
// ★ JSON.parse بدل الكائن الحرفي (المرحلة ٢): توصية V8 الموثقة للبيانات الكبيرة.
// القياس الملزم على حمولتنا (2.44MB، Blob من الذاكرة في كروميوم): 1.27× ثم 0.98× —
// تكافؤ ضمن الضجيج، لا تراجع. أُبقيت الصيغة لتوافق التوصية ولأن ميزتها تتسع مع نمو
// القاموس. الإهراب: الشرطات المائلة ثم الفواصل العليا ثم U+2028/2029 احتياطًا —
// كروم ≥66 يقبلهما خامًا في الحرفيات (اقتراح JSON-superset) لكن الهروب يحمي أي
// أداة قديمة تعيد قراءة الملف.
const jsonText = JSON.stringify(payload)
  .replace(/\\/g, "\\\\")
  .replace(/'/g, "\\'")
  .replace(new RegExp(String.fromCharCode(0x2028), "g"), "\\u2028")
  .replace(new RegExp(String.fromCharCode(0x2029), "g"), "\\u2029");
const js =
  "/* AUTO-GENERATED by code/toolchain/build.mjs — do not edit by hand. */\n" +
  "/* مُولّد آليًّا — لا تُعدّله يدويًّا. عدّل user/dictionaries/*.json ثم أعد البناء. */\n" +
  "globalThis.CLAUDE_L10N = JSON.parse('" + jsonText + "');\n";
fs.writeFileSync(path.join(EXT, "dictionary.js"), js, "utf8");
fs.writeFileSync(path.join(EXT, "languages.json"), JSON.stringify({ default: payload.default, languages: langs }, null, 2) + "\n", "utf8");

console.log(`\nBuilt ${langs.length} language(s) -> user/extension/dictionary.js`);

// --- الإصدار مفصول عن عدّاد القاموس (المرحلة ٠ من خطة الإطلاق) ---
// كان البناء يرفع manifest.version آليًا كلما تغيّر عدد المفردات، وقرارُ المالك تثبيتُ
// 1.0.0 حتى النشر الأول — فأُعيد الرقم يدويًا أربع مرات، وبناءٌ منسيّ واحد قبل الرفع
// كان سيشحن للمتجر رقمًا لا يمكن إنزاله. عمليةٌ يدوية تصحّح عمليةً آلية = عطل ينتظر النسيان.
// الآن: الرقم لا يُمسّ إلا بأمر صريح `--bump patch|minor|major`، وversion_name يُحدَّث
// دائمًا ليحمل عدد المفردات الصادق (فهو وصف لا هوية).
const manifestPath = path.join(EXT, "manifest.json");
if (fs.existsSync(manifestPath)) {
  const mf = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const total = Object.values(dicts).reduce((a, d) => a + Object.keys(d.strings || {}).length, 0);

  const bumpArg = process.argv.find((a) => a.startsWith("--bump"));
  if (bumpArg) {
    const kind = (bumpArg.split("=")[1] || process.argv[process.argv.indexOf(bumpArg) + 1] || "patch").toLowerCase();
    const p = String(mf.version || "1.0.0").split(".").map((x) => parseInt(x, 10) || 0);
    while (p.length < 3) p.push(0);
    if (kind === "major") { p[0]++; p[1] = 0; p[2] = 0; }
    else if (kind === "minor") { p[1]++; p[2] = 0; }
    else p[2]++;
    mf.version = p.join(".");
    console.log(`↑ version -> ${mf.version} (--bump ${kind})`);
  }

  const newName = `${mf.version} — قاموس ${total} عبارة`;
  if (mf.version_name !== newName) {
    mf.version_name = newName;
    console.log(`  version_name -> ${newName}`);
  } else {
    console.log(`= version ${mf.version} (${total} strings)`);
  }
  fs.writeFileSync(manifestPath, JSON.stringify(mf, null, 2) + "\n", "utf8");
}
