// gen-rtl.mjs — مولّد rtl-overrides.css من CSS الموقع الحقيقي (المرحلة ٣).
//
// المدخل: code/sitecss/*.css (لقطة CSS الموقع — تُجدَّد بإعادة تنزيلها عند تحديث
// الموقع، و«طبيب الاتجاه» في صفحة الإعدادات يكشف متى تقادمت).
// المخرج: user/extension/rtl-overrides.css  (قسمان: مصفِّرات ثم منطقيات — الترتيب عقد)
//         user/extension/rtl-coverage.js    (بصمات التغطية التي يقارن بها الطبيب)
//
// منطق القلب كله في user/extension/cml-rtl.js (النسخة الواحدة) — هذا الملف تجميع
// وبوابات فقط. البوابات الثلاث:
//   ١) إعادة تحليل الناتج تمرّ بلا أخطاء وكل قاعدة خلف بوابة data-cml-rtl.
//   ٢) اللاعودة: قلب الناتج نفسه = صفر قلب (فلا قلب مزدوج بنيويًّا).
//   ٣) عتبات صحة المدخل: قواعد كافية وقلب كافٍ — وإلا فالموقع غيّر صيغته والملف
//      القديم يبقى خيرًا من ملف فارغ (exit 1 قبل الكتابة).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
// مسار اللقطة يصمد في البنيتين: مجلد العمل (web/code/sitecss) ونسخة النشر السطحية
// (sitecss/ في الجذر — ينشئه المساهم وينزّل فيه CSS الموقع؛ اللقطة نفسها لا تُنشر).
// ويقبل تمريرًا صريحًا: node gen-rtl.mjs <مجلد اللقطة>
const CANDIDATES = [
  process.argv[2],
  path.resolve(HERE, "..", "sitecss"),        // مجلد العمل: code/sitecss بجوار toolchain
  path.resolve(HERE, "..", "..", "sitecss"),  // نسخة النشر: sitecss في الجذر بجوار tools
].filter(Boolean);
const SITECSS = CANDIDATES.find((p) => { try { return fs.readdirSync(p).some((f) => f.endsWith(".css")); } catch { return false; } });
if (!SITECSS) {
  console.error("! لا لقطة CSS للموقع. أنشئ مجلد sitecss/ ونزّل فيه ملفات CSS من claude.ai ثم أعد التشغيل.");
  console.error("  بُحث في: " + CANDIDATES.join(" | "));
  process.exit(1);
}
const { EXT } = await import(new URL("./paths.mjs", import.meta.url).href);

await import(new URL("../../user/extension/cml-rtl.js", import.meta.url).href);
const R = globalThis.CMLRtl;

// ---- 1) اجمع لقطة الموقع ----
let manifest = null;
try { manifest = JSON.parse(fs.readFileSync(path.join(SITECSS, "_manifest.json"), "utf8")); } catch {}
// ترتيب المستند الحقيقي (من _manifest.json) لا الترتيب الأبجدي: قواعد الموقع غير
// المطبَّقة تتحاكم بالترتيب عند تساوي التخصيص، وترتيبُنا الداخلي يستنسخ ترتيبه
const docOrder = manifest && Array.isArray(manifest.css) ? manifest.css.map((x) => x.file) : [];
const files = fs.readdirSync(SITECSS).filter((f) => f.endsWith(".css")).sort((a, b) => {
  const ia = docOrder.indexOf(a), ib = docOrder.indexOf(b);
  return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib) || a.localeCompare(b);
});
if (!files.length) {
  console.error("! لا ملفات CSS في code/sitecss/ — نزّل لقطة الموقع أولًا.");
  process.exit(1);
}

const all = [];
const layerOrder = [];
let parseErrors = 0;
const parseStats = { animatedPhysical: 0 };
for (const f of files) {
  const p = R.parseCss(fs.readFileSync(path.join(SITECSS, f), "utf8"));
  parseErrors += p.stats.parseErrors;
  parseStats.animatedPhysical += p.stats.animatedPhysical;
  for (const L of p.layerOrder) if (!layerOrder.includes(L)) layerOrder.push(L);
  for (const r of p.rules) { r.idx = all.length; all.push(r); }
  console.log(`+ ${f}: ${p.rules.length} قاعدة${p.stats.parseErrors ? ` (${p.stats.parseErrors} خطأ تحليل)` : ""}`);
}

// ---- 2) اقلب ----
const out = R.flipSheet(all, { layerOrder });
const st = out.stats;
console.log(`\nقواعد الموقع: ${all.length} | مقلوب: ${st.flipped} إعلانًا | مصفِّرات: ${st.neutralized}`);
console.log(`منطقي أصلًا: ${st.logicalAlready} | واعٍ بالاتجاه: ${st.dirAware} (عُزّز منه المشروط بـRTL: ${st.dirBoosted})`);
const unf = Object.entries(st.unflippable).map(([k, v]) => `${k}:${v}`).join(" ");
if (unf) console.log(`متعذّر (يصرّح به الطبيب): ${unf}`);

// ---- 3) بوابات الصحة قبل الكتابة ----
if (parseErrors > 50) { console.error(`! ${parseErrors} خطأ تحليل — صيغة CSS الموقع تغيّرت؟ لن أكتب.`); process.exit(1); }
if (all.length < 1000 || st.flipped < 200) {
  console.error(`! المدخل هزيل (قواعد ${all.length}، قلب ${st.flipped}) — لقطة ناقصة؟ لن أكتب.`);
  process.exit(1);
}

const header =
  "/* AUTO-GENERATED by code/toolchain/gen-rtl.mjs — do not edit by hand.\n" +
  " * مُولّد آليًّا من لقطة CSS الموقع في code/sitecss/ — لا يُعدَّل يدويًّا.\n" +
  " * سلّم تخصيص موحّد: المصفِّرات :not(#..×2) < المنطقيات والمطابقات ×3 < المعزَّزات ×4،\n" +
  " * ومحدِّدات الموقع ملفوفة في :where() (صفر تخصيص) — فالحسم بسلّمنا ثم بترتيب الموقع.\n" +
  " * إعلانات !important في @layer cml-imp (المعلَنة ثانيةً — فالمبكر يغلب في المهمّات،\n" +
  " * وcml-point قبلها محجوزة لإصلاحات base.css النقطية فتبقى لها الكلمة الأخيرة).\n" +
  " * كل قاعدة خلف بوابة " + R.GATE + " — بلا السمة الملفُّ خامل حرفيًّا.\n" +
  " * الأنماط السطرية (المحسوبة بجافاسكربت) لا تُمسّ عمدًا. */\n" +
  "@layer cml-point, cml-imp;\n";
const impRules = out.neutralImp.concat(out.logicalImp, out.dirBoostImp);
const css =
  header +
  "\n/* --- جزر LTR --- */\n" + R.ISLANDS_CSS +
  (impRules.length
    ? "\n/* --- المهمّات (!important) — طبقة مبكرة تقلب قانون الطبقات لصالحنا --- */\n" +
      "@layer cml-imp{\n" + R.serializeRules(impRules) + "\n}\n"
    : "") +
  "\n/* --- المستوى ٢: المصفِّرات --- */\n" + R.serializeRules(out.neutral) +
  "\n\n/* --- المستوى ٣: المنطقيات والنسخ المطابقة --- */\n" + R.serializeRules(out.logical) +
  "\n\n/* --- المستوى ٤: قواعد الموقع المشروطة بـRTL معزَّزةً (قصد المؤلف يفوز) --- */\n" +
  R.serializeRules(out.dirBoost) + "\n";

// بوابة ١: إعادة تحليل الناتج
const re = R.parseCss(css);
if (re.stats.parseErrors > 0) { console.error(`! الناتج لا يُعاد تحليله (${re.stats.parseErrors} خطأ). لن أكتب.`); process.exit(1); }
const ungated = re.rules.filter((r) => !r.sel.startsWith('html[data-cml-rtl="v2"]'));
if (ungated.length) {
  console.error(`! ${ungated.length} قاعدة بلا بوابة، أولها: ${ungated[0].sel.slice(0, 80)}. لن أكتب.`);
  process.exit(1);
}
// بوابة ٢: لا فيزيائيَّ في الناتج — الثابت الحقيقي لمحرّك الاتجاه.
// ★ كانت «اللاعودة» تُعيد قلب الناتج وتتوقع صفرًا، وهو صفرٌ بنيويٌّ لا مُختبَر: كل
// قاعدةٍ تحمل البوابة فيتخطاها المحلّل قبل التحليل أصلًا. والثابت الذي يعنينا حقًّا
// أوضحُ منه: **مستوى المنطقيات لا يحمل خاصيةً فيزيائيةً اتجاهية قط**؛ والمصفِّرات لا
// تحمل إلا unset؛ وfloat/clear احتياطٌ مقصود (لا مقابل منطقيَّ لهما مدعومًا).
// (أما المعزَّزات فتُعيد بثَّ قواعد الموقع المشروطة بـRTL كما كتبها مؤلفها — وفيها
// الفيزيائيُّ عن قصدٍ منه، فهي خارج هذا الفحص عمدًا.)
const PHYS_RE = /^(?:margin|padding|border)-(?:left|right)(?:-|$)|^(?:left|right)$|^border-(?:top|bottom)-(?:left|right)-radius$|^inset-(?:left|right)$|^scroll-(?:margin|padding)-(?:left|right)$/;
const leaks = [];
for (const rule of (out.logical || []).concat(out.logicalImp || [])) {
  for (const d of rule.decls || []) {
    if (d.prop === "float" || d.prop === "clear") continue; // احتياطٌ مقصود
    if (PHYS_RE.test(d.prop)) leaks.push(d.prop + ":" + String(d.value).slice(0, 30) + " ← " + rule.sel.slice(0, 70));
  }
}
for (const rule of (out.neutral || []).concat(out.neutralImp || [])) {
  for (const d of rule.decls || []) {
    if (String(d.value).trim() !== "unset") leaks.push("مصفِّرٌ بقيمةٍ غير unset: " + d.prop + ":" + String(d.value).slice(0, 30));
  }
}
if (leaks.length) {
  console.error(`! فيزيائيٌّ تسرّب إلى الناتج (${leaks.length})، أوله:`);
  for (const l of leaks.slice(0, 5)) console.error("   " + l);
  process.exit(1);
}
console.log(`  لا فيزيائيَّ في المنطقيات (${(out.logical || []).length + (out.logicalImp || []).length} قاعدة)، والمصفِّرات unset كلها`);

// ---- 4) اكتب ----
fs.writeFileSync(path.join(EXT, "rtl-overrides.css"), css, "utf8");
const cov =
  "/* AUTO-GENERATED by code/toolchain/gen-rtl.mjs — بصمات تغطية محرّك الاتجاه.\n" +
  " * يقارن بها «طبيب الاتجاه» CSS الموقعَ الحيّ ليكشف ما استجدّ ولا نغطيه. */\n" +
  "globalThis.CMLRtlCoverage = " + JSON.stringify({
    flipped: st.flipped,
    sources: manifest && Array.isArray(manifest.css) ? manifest.css.map((x) => ({ file: x.file, sha: x.sha256 })) : files.map((f) => ({ file: f })),
    keys: out.coverage,
  }) + ";\n";
fs.writeFileSync(path.join(EXT, "rtl-coverage.js"), cov, "utf8");

console.log(`\n✓ rtl-overrides.css: ${(css.length / 1024).toFixed(1)}KB (تصفير ${out.neutral.length} + منطقي/مطابق ${out.logical.length} + معزَّز ${out.dirBoost.length} + مهمّات ${impRules.length})`);
console.log(`  نسخ مطابقة: ${st.identity} إعلانًا | حركات اتجاهية (تُبلَّغ لا تُقلب): ${parseStats.animatedPhysical}`);
console.log(`✓ rtl-coverage.js: ${out.coverage.length} بصمة`);
console.log("✓ البوابات الثلاث: إعادة التحليل، البوابة على كل قاعدة، لا فيزيائيَّ في الناتج");
